### PR TITLE
Fixes #56.

### LINKED ISSUE #56: JS to sign an initiative is broken
Signing an initiative shows a weird layout. Refreshing the page shows the correct one:

The same behaviour is found when unsigning the initiative.

### PR DESCRIPTION
**Pull request by jsperezg**
* Adjustments in the javascript code responsible of maintaining the totals.
* Added gems in Gemfile required to be able to debug from Rubymine environments.
* Changes in bin/rails that make feasible to execute rails s from root folder and get the dummy app running.

### CODE REVIEW

File: app/views/decidim/initiatives/initiative_votes/update_buttons_and_counters.js.erb [hunk 1]
```diff
@@ -5,7 +5,7 @@
       userIdentitiesDialog = $('#user-identities'),
       refreshUrl;
 
-  morphdom($initiativeVotesCount[0], '<%= j(render partial: 'decidim/initiatives/initiatives/votes_count', locals: { initiative: current_initiative }) %>');
+  $initiativeVotesCount.html('<%= j(render partial: 'decidim/initiatives/initiatives/votes_count', locals: { initiative: current_initiative }) %>');
```
Comment (josepjaume) [inline app/views/decidim/initiatives/initiative_votes/update_buttons_and_counters.js.erb]: Just out of curiosity: Is `morphdom` causing issues here? It's generally useful to mutate state with it, as it won't replace the whole dom (thus being more performant and also preventing breaking micro-states like `hover`, etc).

Comment (jsperezg) [reply app/views/decidim/initiatives/initiative_votes/update_buttons_and_counters.js.erb]: As it was implemented morphdom was causing the issue. 

Anyway this patch must be interpreted in the current project context. It's a short week and we want to deliver an stable version ASAP. 

I agree with you that morphdom has many advantages over changing the entire dom. Maybe for an upcoming version we could invest more time and try to make it work using morphdom.

Comment (josepjaume) [reply app/views/decidim/initiatives/initiative_votes/update_buttons_and_counters.js.erb]: No worries, just wanted to know if you figured out the exact issue or resorted to a more conservative solution (which seems okay in this context!). Good job!
